import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { cookies } from "next/headers";
import { auth } from '@/config/firebaseAdmin';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Questionist",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
