import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { getSession } from "@/actions/getSession";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Questionist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar session={session}/>
        {children}
      </body>
    </html>
  );
}
